/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R1xgamesRouteImport } from './routes/1xgames'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as AppRouteImport } from './routes/app'
import { Route as BadmintonRouteImport } from './routes/badminton'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as BecomeAgentRouteImport } from './routes/become-agent'
import { Route as BoxingRouteImport } from './routes/boxing'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CricketRouteImport } from './routes/cricket'
import { Route as CricketLiveRouteImport } from './routes/cricket-live'
import { Route as CricketOddsRouteImport } from './routes/cricket-odds'
import { Route as CricketResultsRouteImport } from './routes/cricket-results'
import { Route as CricketScheduleRouteImport } from './routes/cricket-schedule'
import { Route as Cs2BettingRouteImport } from './routes/cs2-betting'
import { Route as Dota2BettingRouteImport } from './routes/dota2-betting'
import { Route as EsportsRouteImport } from './routes/esports'
import { Route as EsportsResultsRouteImport } from './routes/esports-results'
import { Route as EsportsScheduleRouteImport } from './routes/esports-schedule'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FootballRouteImport } from './routes/football'
import { Route as FullVersionRouteImport } from './routes/full-version'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IceHockeyRouteImport } from './routes/ice-hockey'
import { Route as IosRouteImport } from './routes/ios'
import { Route as IplBettingRouteImport } from './routes/ipl-betting'
import { Route as KabaddiRouteImport } from './routes/kabaddi'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LiveCasinoRouteImport } from './routes/live-casino'
import { Route as LolBettingRouteImport } from './routes/lol-betting'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MultiLiveRouteImport } from './routes/multi-live'
import { Route as OtherAppsRouteImport } from './routes/other-apps'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ResponsibleGamingRouteImport } from './routes/responsible-gaming'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TableTennisRouteImport } from './routes/table-tennis'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TopEventsRouteImport } from './routes/top-events'
import { Route as TotoRouteImport } from './routes/toto'
import { Route as ValorantBettingRouteImport } from './routes/valorant-betting'
import { Route as VolleyballRouteImport } from './routes/volleyball'
import { Route as FootballOddsRouteImport } from './routes/football_.odds'
import { Route as FootballScheduleRouteImport } from './routes/football_.schedule'
import { Route as FootballTipsRouteImport } from './routes/football_.tips'
import { Route as TennisAtpRouteImport } from './routes/tennis_.atp'
import { Route as TennisGrandSlamsRouteImport } from './routes/tennis_.grand-slams'
import { Route as TennisResultsRouteImport } from './routes/tennis_.results'
import { Route as TennisScheduleRouteImport } from './routes/tennis_.schedule'
import { Route as TennisWtaRouteImport } from './routes/tennis_.wta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R1xgamesRoute = R1xgamesRouteImport.update({
  id: '/1xgames',
  path: '/1xgames',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BadmintonRoute = BadmintonRouteImport.update({
  id: '/badminton',
  path: '/badminton',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAgentRoute = BecomeAgentRouteImport.update({
  id: '/become-agent',
  path: '/become-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxingRoute = BoxingRouteImport.update({
  id: '/boxing',
  path: '/boxing',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketRoute = CricketRouteImport.update({
  id: '/cricket',
  path: '/cricket',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketLiveRoute = CricketLiveRouteImport.update({
  id: '/cricket-live',
  path: '/cricket-live',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketOddsRoute = CricketOddsRouteImport.update({
  id: '/cricket-odds',
  path: '/cricket-odds',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketResultsRoute = CricketResultsRouteImport.update({
  id: '/cricket-results',
  path: '/cricket-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketScheduleRoute = CricketScheduleRouteImport.update({
  id: '/cricket-schedule',
  path: '/cricket-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const Cs2BettingRoute = Cs2BettingRouteImport.update({
  id: '/cs2-betting',
  path: '/cs2-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const Dota2BettingRoute = Dota2BettingRouteImport.update({
  id: '/dota2-betting',
  path: '/dota2-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsRoute = EsportsRouteImport.update({
  id: '/esports',
  path: '/esports',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsResultsRoute = EsportsResultsRouteImport.update({
  id: '/esports-results',
  path: '/esports-results',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsScheduleRoute = EsportsScheduleRouteImport.update({
  id: '/esports-schedule',
  path: '/esports-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const FullVersionRoute = FullVersionRouteImport.update({
  id: '/full-version',
  path: '/full-version',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IceHockeyRoute = IceHockeyRouteImport.update({
  id: '/ice-hockey',
  path: '/ice-hockey',
  getParentRoute: () => rootRouteImport,
} as any)
const IosRoute = IosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const IplBettingRoute = IplBettingRouteImport.update({
  id: '/ipl-betting',
  path: '/ipl-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const KabaddiRoute = KabaddiRouteImport.update({
  id: '/kabaddi',
  path: '/kabaddi',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCasinoRoute = LiveCasinoRouteImport.update({
  id: '/live-casino',
  path: '/live-casino',
  getParentRoute: () => rootRouteImport,
} as any)
const LolBettingRoute = LolBettingRouteImport.update({
  id: '/lol-betting',
  path: '/lol-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiLiveRoute = MultiLiveRouteImport.update({
  id: '/multi-live',
  path: '/multi-live',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherAppsRoute = OtherAppsRouteImport.update({
  id: '/other-apps',
  path: '/other-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamingRoute = ResponsibleGamingRouteImport.update({
  id: '/responsible-gaming',
  path: '/responsible-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTennisRoute = TableTennisRouteImport.update({
  id: '/table-tennis',
  path: '/table-tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TopEventsRoute = TopEventsRouteImport.update({
  id: '/top-events',
  path: '/top-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TotoRoute = TotoRouteImport.update({
  id: '/toto',
  path: '/toto',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorantBettingRoute = ValorantBettingRouteImport.update({
  id: '/valorant-betting',
  path: '/valorant-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const VolleyballRoute = VolleyballRouteImport.update({
  id: '/volleyball',
  path: '/volleyball',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballOddsRoute = FootballOddsRouteImport.update({
  id: '/football_/odds',
  path: '/football/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballScheduleRoute = FootballScheduleRouteImport.update({
  id: '/football_/schedule',
  path: '/football/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballTipsRoute = FootballTipsRouteImport.update({
  id: '/football_/tips',
  path: '/football/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisAtpRoute = TennisAtpRouteImport.update({
  id: '/tennis_/atp',
  path: '/tennis/atp',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisGrandSlamsRoute = TennisGrandSlamsRouteImport.update({
  id: '/tennis_/grand-slams',
  path: '/tennis/grand-slams',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisResultsRoute = TennisResultsRouteImport.update({
  id: '/tennis_/results',
  path: '/tennis/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisScheduleRoute = TennisScheduleRouteImport.update({
  id: '/tennis_/schedule',
  path: '/tennis/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisWtaRoute = TennisWtaRouteImport.update({
  id: '/tennis_/wta',
  path: '/tennis/wta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1xgames': typeof R1xgamesRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/android': typeof AndroidRoute
  '/app': typeof AppRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/boxing': typeof BoxingRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/cricket': typeof CricketRoute
  '/cricket-live': typeof CricketLiveRoute
  '/cricket-odds': typeof CricketOddsRoute
  '/cricket-results': typeof CricketResultsRoute
  '/cricket-schedule': typeof CricketScheduleRoute
  '/cs2-betting': typeof Cs2BettingRoute
  '/dota2-betting': typeof Dota2BettingRoute
  '/esports': typeof EsportsRoute
  '/esports-results': typeof EsportsResultsRoute
  '/esports-schedule': typeof EsportsScheduleRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/full-version': typeof FullVersionRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/ice-hockey': typeof IceHockeyRoute
  '/ios': typeof IosRoute
  '/ipl-betting': typeof IplBettingRoute
  '/kabaddi': typeof KabaddiRoute
  '/live': typeof LiveRoute
  '/live-casino': typeof LiveCasinoRoute
  '/lol-betting': typeof LolBettingRoute
  '/mobile': typeof MobileRoute
  '/more': typeof MoreRoute
  '/multi-live': typeof MultiLiveRoute
  '/other-apps': typeof OtherAppsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/promotions': typeof PromotionsRoute
  '/registration': typeof RegistrationRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/results': typeof ResultsRoute
  '/sports': typeof SportsRoute
  '/statistics': typeof StatisticsRoute
  '/table-tennis': typeof TableTennisRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/top-events': typeof TopEventsRoute
  '/toto': typeof TotoRoute
  '/valorant-betting': typeof ValorantBettingRoute
  '/volleyball': typeof VolleyballRoute
  '/football/odds': typeof FootballOddsRoute
  '/football/schedule': typeof FootballScheduleRoute
  '/football/tips': typeof FootballTipsRoute
  '/tennis/atp': typeof TennisAtpRoute
  '/tennis/grand-slams': typeof TennisGrandSlamsRoute
  '/tennis/results': typeof TennisResultsRoute
  '/tennis/schedule': typeof TennisScheduleRoute
  '/tennis/wta': typeof TennisWtaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1xgames': typeof R1xgamesRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/android': typeof AndroidRoute
  '/app': typeof AppRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/boxing': typeof BoxingRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/cricket': typeof CricketRoute
  '/cricket-live': typeof CricketLiveRoute
  '/cricket-odds': typeof CricketOddsRoute
  '/cricket-results': typeof CricketResultsRoute
  '/cricket-schedule': typeof CricketScheduleRoute
  '/cs2-betting': typeof Cs2BettingRoute
  '/dota2-betting': typeof Dota2BettingRoute
  '/esports': typeof EsportsRoute
  '/esports-results': typeof EsportsResultsRoute
  '/esports-schedule': typeof EsportsScheduleRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/full-version': typeof FullVersionRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/ice-hockey': typeof IceHockeyRoute
  '/ios': typeof IosRoute
  '/ipl-betting': typeof IplBettingRoute
  '/kabaddi': typeof KabaddiRoute
  '/live': typeof LiveRoute
  '/live-casino': typeof LiveCasinoRoute
  '/lol-betting': typeof LolBettingRoute
  '/mobile': typeof MobileRoute
  '/more': typeof MoreRoute
  '/multi-live': typeof MultiLiveRoute
  '/other-apps': typeof OtherAppsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/promotions': typeof PromotionsRoute
  '/registration': typeof RegistrationRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/results': typeof ResultsRoute
  '/sports': typeof SportsRoute
  '/statistics': typeof StatisticsRoute
  '/table-tennis': typeof TableTennisRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/top-events': typeof TopEventsRoute
  '/toto': typeof TotoRoute
  '/valorant-betting': typeof ValorantBettingRoute
  '/volleyball': typeof VolleyballRoute
  '/football/odds': typeof FootballOddsRoute
  '/football/schedule': typeof FootballScheduleRoute
  '/football/tips': typeof FootballTipsRoute
  '/tennis/atp': typeof TennisAtpRoute
  '/tennis/grand-slams': typeof TennisGrandSlamsRoute
  '/tennis/results': typeof TennisResultsRoute
  '/tennis/schedule': typeof TennisScheduleRoute
  '/tennis/wta': typeof TennisWtaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1xgames': typeof R1xgamesRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/android': typeof AndroidRoute
  '/app': typeof AppRoute
  '/badminton': typeof BadmintonRoute
  '/basketball': typeof BasketballRoute
  '/become-agent': typeof BecomeAgentRoute
  '/boxing': typeof BoxingRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/cookies': typeof CookiesRoute
  '/cricket': typeof CricketRoute
  '/cricket-live': typeof CricketLiveRoute
  '/cricket-odds': typeof CricketOddsRoute
  '/cricket-results': typeof CricketResultsRoute
  '/cricket-schedule': typeof CricketScheduleRoute
  '/cs2-betting': typeof Cs2BettingRoute
  '/dota2-betting': typeof Dota2BettingRoute
  '/esports': typeof EsportsRoute
  '/esports-results': typeof EsportsResultsRoute
  '/esports-schedule': typeof EsportsScheduleRoute
  '/faq': typeof FaqRoute
  '/football': typeof FootballRoute
  '/full-version': typeof FullVersionRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/ice-hockey': typeof IceHockeyRoute
  '/ios': typeof IosRoute
  '/ipl-betting': typeof IplBettingRoute
  '/kabaddi': typeof KabaddiRoute
  '/live': typeof LiveRoute
  '/live-casino': typeof LiveCasinoRoute
  '/lol-betting': typeof LolBettingRoute
  '/mobile': typeof MobileRoute
  '/more': typeof MoreRoute
  '/multi-live': typeof MultiLiveRoute
  '/other-apps': typeof OtherAppsRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/promotions': typeof PromotionsRoute
  '/registration': typeof RegistrationRoute
  '/responsible-gaming': typeof ResponsibleGamingRoute
  '/results': typeof ResultsRoute
  '/sports': typeof SportsRoute
  '/statistics': typeof StatisticsRoute
  '/table-tennis': typeof TableTennisRoute
  '/tennis': typeof TennisRoute
  '/terms': typeof TermsRoute
  '/top-events': typeof TopEventsRoute
  '/toto': typeof TotoRoute
  '/valorant-betting': typeof ValorantBettingRoute
  '/volleyball': typeof VolleyballRoute
  '/football_/odds': typeof FootballOddsRoute
  '/football_/schedule': typeof FootballScheduleRoute
  '/football_/tips': typeof FootballTipsRoute
  '/tennis_/atp': typeof TennisAtpRoute
  '/tennis_/grand-slams': typeof TennisGrandSlamsRoute
  '/tennis_/results': typeof TennisResultsRoute
  '/tennis_/schedule': typeof TennisScheduleRoute
  '/tennis_/wta': typeof TennisWtaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1xgames'
    | '/about'
    | '/affiliate'
    | '/android'
    | '/app'
    | '/badminton'
    | '/basketball'
    | '/become-agent'
    | '/boxing'
    | '/casino'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/cricket'
    | '/cricket-live'
    | '/cricket-odds'
    | '/cricket-results'
    | '/cricket-schedule'
    | '/cs2-betting'
    | '/dota2-betting'
    | '/esports'
    | '/esports-results'
    | '/esports-schedule'
    | '/faq'
    | '/football'
    | '/full-version'
    | '/games'
    | '/help'
    | '/ice-hockey'
    | '/ios'
    | '/ipl-betting'
    | '/kabaddi'
    | '/live'
    | '/live-casino'
    | '/lol-betting'
    | '/mobile'
    | '/more'
    | '/multi-live'
    | '/other-apps'
    | '/payment-methods'
    | '/payments'
    | '/privacy'
    | '/promo'
    | '/promotions'
    | '/registration'
    | '/responsible-gaming'
    | '/results'
    | '/sports'
    | '/statistics'
    | '/table-tennis'
    | '/tennis'
    | '/terms'
    | '/top-events'
    | '/toto'
    | '/valorant-betting'
    | '/volleyball'
    | '/football/odds'
    | '/football/schedule'
    | '/football/tips'
    | '/tennis/atp'
    | '/tennis/grand-slams'
    | '/tennis/results'
    | '/tennis/schedule'
    | '/tennis/wta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1xgames'
    | '/about'
    | '/affiliate'
    | '/android'
    | '/app'
    | '/badminton'
    | '/basketball'
    | '/become-agent'
    | '/boxing'
    | '/casino'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/cricket'
    | '/cricket-live'
    | '/cricket-odds'
    | '/cricket-results'
    | '/cricket-schedule'
    | '/cs2-betting'
    | '/dota2-betting'
    | '/esports'
    | '/esports-results'
    | '/esports-schedule'
    | '/faq'
    | '/football'
    | '/full-version'
    | '/games'
    | '/help'
    | '/ice-hockey'
    | '/ios'
    | '/ipl-betting'
    | '/kabaddi'
    | '/live'
    | '/live-casino'
    | '/lol-betting'
    | '/mobile'
    | '/more'
    | '/multi-live'
    | '/other-apps'
    | '/payment-methods'
    | '/payments'
    | '/privacy'
    | '/promo'
    | '/promotions'
    | '/registration'
    | '/responsible-gaming'
    | '/results'
    | '/sports'
    | '/statistics'
    | '/table-tennis'
    | '/tennis'
    | '/terms'
    | '/top-events'
    | '/toto'
    | '/valorant-betting'
    | '/volleyball'
    | '/football/odds'
    | '/football/schedule'
    | '/football/tips'
    | '/tennis/atp'
    | '/tennis/grand-slams'
    | '/tennis/results'
    | '/tennis/schedule'
    | '/tennis/wta'
  id:
    | '__root__'
    | '/'
    | '/1xgames'
    | '/about'
    | '/affiliate'
    | '/android'
    | '/app'
    | '/badminton'
    | '/basketball'
    | '/become-agent'
    | '/boxing'
    | '/casino'
    | '/contact'
    | '/contacts'
    | '/cookies'
    | '/cricket'
    | '/cricket-live'
    | '/cricket-odds'
    | '/cricket-results'
    | '/cricket-schedule'
    | '/cs2-betting'
    | '/dota2-betting'
    | '/esports'
    | '/esports-results'
    | '/esports-schedule'
    | '/faq'
    | '/football'
    | '/full-version'
    | '/games'
    | '/help'
    | '/ice-hockey'
    | '/ios'
    | '/ipl-betting'
    | '/kabaddi'
    | '/live'
    | '/live-casino'
    | '/lol-betting'
    | '/mobile'
    | '/more'
    | '/multi-live'
    | '/other-apps'
    | '/payment-methods'
    | '/payments'
    | '/privacy'
    | '/promo'
    | '/promotions'
    | '/registration'
    | '/responsible-gaming'
    | '/results'
    | '/sports'
    | '/statistics'
    | '/table-tennis'
    | '/tennis'
    | '/terms'
    | '/top-events'
    | '/toto'
    | '/valorant-betting'
    | '/volleyball'
    | '/football_/odds'
    | '/football_/schedule'
    | '/football_/tips'
    | '/tennis_/atp'
    | '/tennis_/grand-slams'
    | '/tennis_/results'
    | '/tennis_/schedule'
    | '/tennis_/wta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1xgamesRoute: typeof R1xgamesRoute
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  AndroidRoute: typeof AndroidRoute
  AppRoute: typeof AppRoute
  BadmintonRoute: typeof BadmintonRoute
  BasketballRoute: typeof BasketballRoute
  BecomeAgentRoute: typeof BecomeAgentRoute
  BoxingRoute: typeof BoxingRoute
  CasinoRoute: typeof CasinoRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  CookiesRoute: typeof CookiesRoute
  CricketRoute: typeof CricketRoute
  CricketLiveRoute: typeof CricketLiveRoute
  CricketOddsRoute: typeof CricketOddsRoute
  CricketResultsRoute: typeof CricketResultsRoute
  CricketScheduleRoute: typeof CricketScheduleRoute
  Cs2BettingRoute: typeof Cs2BettingRoute
  Dota2BettingRoute: typeof Dota2BettingRoute
  EsportsRoute: typeof EsportsRoute
  EsportsResultsRoute: typeof EsportsResultsRoute
  EsportsScheduleRoute: typeof EsportsScheduleRoute
  FaqRoute: typeof FaqRoute
  FootballRoute: typeof FootballRoute
  FullVersionRoute: typeof FullVersionRoute
  GamesRoute: typeof GamesRoute
  HelpRoute: typeof HelpRoute
  IceHockeyRoute: typeof IceHockeyRoute
  IosRoute: typeof IosRoute
  IplBettingRoute: typeof IplBettingRoute
  KabaddiRoute: typeof KabaddiRoute
  LiveRoute: typeof LiveRoute
  LiveCasinoRoute: typeof LiveCasinoRoute
  LolBettingRoute: typeof LolBettingRoute
  MobileRoute: typeof MobileRoute
  MoreRoute: typeof MoreRoute
  MultiLiveRoute: typeof MultiLiveRoute
  OtherAppsRoute: typeof OtherAppsRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  PromoRoute: typeof PromoRoute
  PromotionsRoute: typeof PromotionsRoute
  RegistrationRoute: typeof RegistrationRoute
  ResponsibleGamingRoute: typeof ResponsibleGamingRoute
  ResultsRoute: typeof ResultsRoute
  SportsRoute: typeof SportsRoute
  StatisticsRoute: typeof StatisticsRoute
  TableTennisRoute: typeof TableTennisRoute
  TennisRoute: typeof TennisRoute
  TermsRoute: typeof TermsRoute
  TopEventsRoute: typeof TopEventsRoute
  TotoRoute: typeof TotoRoute
  ValorantBettingRoute: typeof ValorantBettingRoute
  VolleyballRoute: typeof VolleyballRoute
  FootballOddsRoute: typeof FootballOddsRoute
  FootballScheduleRoute: typeof FootballScheduleRoute
  FootballTipsRoute: typeof FootballTipsRoute
  TennisAtpRoute: typeof TennisAtpRoute
  TennisGrandSlamsRoute: typeof TennisGrandSlamsRoute
  TennisResultsRoute: typeof TennisResultsRoute
  TennisScheduleRoute: typeof TennisScheduleRoute
  TennisWtaRoute: typeof TennisWtaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1xgames': {
      id: '/1xgames'
      path: '/1xgames'
      fullPath: '/1xgames'
      preLoaderRoute: typeof R1xgamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badminton': {
      id: '/badminton'
      path: '/badminton'
      fullPath: '/badminton'
      preLoaderRoute: typeof BadmintonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-agent': {
      id: '/become-agent'
      path: '/become-agent'
      fullPath: '/become-agent'
      preLoaderRoute: typeof BecomeAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxing': {
      id: '/boxing'
      path: '/boxing'
      fullPath: '/boxing'
      preLoaderRoute: typeof BoxingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket': {
      id: '/cricket'
      path: '/cricket'
      fullPath: '/cricket'
      preLoaderRoute: typeof CricketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-live': {
      id: '/cricket-live'
      path: '/cricket-live'
      fullPath: '/cricket-live'
      preLoaderRoute: typeof CricketLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-odds': {
      id: '/cricket-odds'
      path: '/cricket-odds'
      fullPath: '/cricket-odds'
      preLoaderRoute: typeof CricketOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-results': {
      id: '/cricket-results'
      path: '/cricket-results'
      fullPath: '/cricket-results'
      preLoaderRoute: typeof CricketResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-schedule': {
      id: '/cricket-schedule'
      path: '/cricket-schedule'
      fullPath: '/cricket-schedule'
      preLoaderRoute: typeof CricketScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs2-betting': {
      id: '/cs2-betting'
      path: '/cs2-betting'
      fullPath: '/cs2-betting'
      preLoaderRoute: typeof Cs2BettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dota2-betting': {
      id: '/dota2-betting'
      path: '/dota2-betting'
      fullPath: '/dota2-betting'
      preLoaderRoute: typeof Dota2BettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports': {
      id: '/esports'
      path: '/esports'
      fullPath: '/esports'
      preLoaderRoute: typeof EsportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports-results': {
      id: '/esports-results'
      path: '/esports-results'
      fullPath: '/esports-results'
      preLoaderRoute: typeof EsportsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports-schedule': {
      id: '/esports-schedule'
      path: '/esports-schedule'
      fullPath: '/esports-schedule'
      preLoaderRoute: typeof EsportsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-version': {
      id: '/full-version'
      path: '/full-version'
      fullPath: '/full-version'
      preLoaderRoute: typeof FullVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ice-hockey': {
      id: '/ice-hockey'
      path: '/ice-hockey'
      fullPath: '/ice-hockey'
      preLoaderRoute: typeof IceHockeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios': {
      id: '/ios'
      path: '/ios'
      fullPath: '/ios'
      preLoaderRoute: typeof IosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipl-betting': {
      id: '/ipl-betting'
      path: '/ipl-betting'
      fullPath: '/ipl-betting'
      preLoaderRoute: typeof IplBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabaddi': {
      id: '/kabaddi'
      path: '/kabaddi'
      fullPath: '/kabaddi'
      preLoaderRoute: typeof KabaddiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-casino': {
      id: '/live-casino'
      path: '/live-casino'
      fullPath: '/live-casino'
      preLoaderRoute: typeof LiveCasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol-betting': {
      id: '/lol-betting'
      path: '/lol-betting'
      fullPath: '/lol-betting'
      preLoaderRoute: typeof LolBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-live': {
      id: '/multi-live'
      path: '/multi-live'
      fullPath: '/multi-live'
      preLoaderRoute: typeof MultiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-apps': {
      id: '/other-apps'
      path: '/other-apps'
      fullPath: '/other-apps'
      preLoaderRoute: typeof OtherAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gaming': {
      id: '/responsible-gaming'
      path: '/responsible-gaming'
      fullPath: '/responsible-gaming'
      preLoaderRoute: typeof ResponsibleGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-tennis': {
      id: '/table-tennis'
      path: '/table-tennis'
      fullPath: '/table-tennis'
      preLoaderRoute: typeof TableTennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-events': {
      id: '/top-events'
      path: '/top-events'
      fullPath: '/top-events'
      preLoaderRoute: typeof TopEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toto': {
      id: '/toto'
      path: '/toto'
      fullPath: '/toto'
      preLoaderRoute: typeof TotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valorant-betting': {
      id: '/valorant-betting'
      path: '/valorant-betting'
      fullPath: '/valorant-betting'
      preLoaderRoute: typeof ValorantBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volleyball': {
      id: '/volleyball'
      path: '/volleyball'
      fullPath: '/volleyball'
      preLoaderRoute: typeof VolleyballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football_/odds': {
      id: '/football_/odds'
      path: '/football/odds'
      fullPath: '/football/odds'
      preLoaderRoute: typeof FootballOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football_/schedule': {
      id: '/football_/schedule'
      path: '/football/schedule'
      fullPath: '/football/schedule'
      preLoaderRoute: typeof FootballScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football_/tips': {
      id: '/football_/tips'
      path: '/football/tips'
      fullPath: '/football/tips'
      preLoaderRoute: typeof FootballTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis_/atp': {
      id: '/tennis_/atp'
      path: '/tennis/atp'
      fullPath: '/tennis/atp'
      preLoaderRoute: typeof TennisAtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis_/grand-slams': {
      id: '/tennis_/grand-slams'
      path: '/tennis/grand-slams'
      fullPath: '/tennis/grand-slams'
      preLoaderRoute: typeof TennisGrandSlamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis_/results': {
      id: '/tennis_/results'
      path: '/tennis/results'
      fullPath: '/tennis/results'
      preLoaderRoute: typeof TennisResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis_/schedule': {
      id: '/tennis_/schedule'
      path: '/tennis/schedule'
      fullPath: '/tennis/schedule'
      preLoaderRoute: typeof TennisScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis_/wta': {
      id: '/tennis_/wta'
      path: '/tennis/wta'
      fullPath: '/tennis/wta'
      preLoaderRoute: typeof TennisWtaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1xgamesRoute: R1xgamesRoute,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  AndroidRoute: AndroidRoute,
  AppRoute: AppRoute,
  BadmintonRoute: BadmintonRoute,
  BasketballRoute: BasketballRoute,
  BecomeAgentRoute: BecomeAgentRoute,
  BoxingRoute: BoxingRoute,
  CasinoRoute: CasinoRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  CookiesRoute: CookiesRoute,
  CricketRoute: CricketRoute,
  CricketLiveRoute: CricketLiveRoute,
  CricketOddsRoute: CricketOddsRoute,
  CricketResultsRoute: CricketResultsRoute,
  CricketScheduleRoute: CricketScheduleRoute,
  Cs2BettingRoute: Cs2BettingRoute,
  Dota2BettingRoute: Dota2BettingRoute,
  EsportsRoute: EsportsRoute,
  EsportsResultsRoute: EsportsResultsRoute,
  EsportsScheduleRoute: EsportsScheduleRoute,
  FaqRoute: FaqRoute,
  FootballRoute: FootballRoute,
  FullVersionRoute: FullVersionRoute,
  GamesRoute: GamesRoute,
  HelpRoute: HelpRoute,
  IceHockeyRoute: IceHockeyRoute,
  IosRoute: IosRoute,
  IplBettingRoute: IplBettingRoute,
  KabaddiRoute: KabaddiRoute,
  LiveRoute: LiveRoute,
  LiveCasinoRoute: LiveCasinoRoute,
  LolBettingRoute: LolBettingRoute,
  MobileRoute: MobileRoute,
  MoreRoute: MoreRoute,
  MultiLiveRoute: MultiLiveRoute,
  OtherAppsRoute: OtherAppsRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  PromoRoute: PromoRoute,
  PromotionsRoute: PromotionsRoute,
  RegistrationRoute: RegistrationRoute,
  ResponsibleGamingRoute: ResponsibleGamingRoute,
  ResultsRoute: ResultsRoute,
  SportsRoute: SportsRoute,
  StatisticsRoute: StatisticsRoute,
  TableTennisRoute: TableTennisRoute,
  TennisRoute: TennisRoute,
  TermsRoute: TermsRoute,
  TopEventsRoute: TopEventsRoute,
  TotoRoute: TotoRoute,
  ValorantBettingRoute: ValorantBettingRoute,
  VolleyballRoute: VolleyballRoute,
  FootballOddsRoute: FootballOddsRoute,
  FootballScheduleRoute: FootballScheduleRoute,
  FootballTipsRoute: FootballTipsRoute,
  TennisAtpRoute: TennisAtpRoute,
  TennisGrandSlamsRoute: TennisGrandSlamsRoute,
  TennisResultsRoute: TennisResultsRoute,
  TennisScheduleRoute: TennisScheduleRoute,
  TennisWtaRoute: TennisWtaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
